openapi: 3.0.0
info:
  title: TestUserFeature API
  version: 1.0.0
  description: API for managing testuserfeature entities

paths:
  /testuserfeatures:
    get:
      summary: List all testuserfeatures
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestUserFeature'
    post:
      summary: Create a new testuserfeature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTestUserFeatureRequest'
      responses:
        '201':
          description: TestUserFeature created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestUserFeature'

  /testuserfeatures/{id}:
    get:
      summary: Get testuserfeature by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestUserFeature'

components:
  schemas:
    TestUserFeature:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
    
    CreateTestUserFeatureRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
