package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// analyzeResult holds the outcome of a single analysis rule.
type analyzeResult struct {
	category   string // Architecture, Quality, Security, Standards, Tests, Dependencies
	rule       string
	status     string // "✓", "✗", "⚠"
	message    string
	suggestion string
	file       string // affected file or directory, empty if project-wide
}

// analyzeOptions controls what categories are run.
type analyzeOptions struct {
	architecture bool
	quality      bool
	security     bool
	standards    bool
	tests        bool
	deps         bool
	output       string // "text" or "json"
	failOnWarn   bool
}

var analyzeCmd = &cobra.Command{
	Use:   "analyze",
	Short: "Deep self-analysis of the generated project for quality and correctness",
	Long: `analyze performs a comprehensive audit of the current project generated by Goca.

It verifies:
  Architecture  — Clean Architecture layer boundaries, import directions, DI wiring
  Quality       — Cyclomatic hints, unused packages, empty files, naming conventions
  Security      — OWASP A03 checks: missing input validation, hardcoded secrets, SQL patterns
  Standards     — Go conventions: package names, file naming, exported doc comments
  Tests         — Test coverage files exist, table-driven patterns, mock presence
  Dependencies  — go.mod tidiness, known-insecure module versions, replace directives

Output is a categorised report with pass/warn/fail per rule and actionable suggestions.

Flags:
  --arch        Only run architecture checks
  --quality     Only run quality checks
  --security    Only run security checks
  --standards   Only run standards checks
  --tests       Only run test checks
  --deps        Only run dependency checks
  (no category flag = all categories)

Exit codes:
  0  All checks passed
  1  One or more checks FAILED
  2  No checks failed but warnings present (when --fail-on-warn)`,
	RunE: runAnalyze,
}

var analyzeOpts analyzeOptions

func init() {
	analyzeCmd.Flags().BoolVar(&analyzeOpts.architecture, "arch", false, "Only run architecture checks")
	analyzeCmd.Flags().BoolVar(&analyzeOpts.quality, "quality", false, "Only run quality checks")
	analyzeCmd.Flags().BoolVar(&analyzeOpts.security, "security", false, "Only run security checks")
	analyzeCmd.Flags().BoolVar(&analyzeOpts.standards, "standards", false, "Only run standards checks")
	analyzeCmd.Flags().BoolVar(&analyzeOpts.tests, "tests", false, "Only run test checks")
	analyzeCmd.Flags().BoolVar(&analyzeOpts.deps, "deps", false, "Only run dependency checks")
	analyzeCmd.Flags().StringVar(&analyzeOpts.output, "output", "text", "Output format: text or json")
	analyzeCmd.Flags().BoolVar(&analyzeOpts.failOnWarn, "fail-on-warn", false, "Exit with code 2 when warnings are present")
}

func runAnalyze(cmd *cobra.Command, args []string) error {
	ui.Header("Goca Analyze — Deep Project Self-Analysis")
	ui.Blank()

	opts := resolveAnalyzeCategories(analyzeOpts)

	var results []analyzeResult

	ui.Step(1, "Architecture analysis")
	if opts.architecture {
		results = append(results, runArchitectureChecks()...)
	}

	ui.Step(2, "Code quality analysis")
	if opts.quality {
		results = append(results, runQualityChecks()...)
	}

	ui.Step(3, "Security analysis")
	if opts.security {
		results = append(results, runSecurityChecks()...)
	}

	ui.Step(4, "Standards analysis")
	if opts.standards {
		results = append(results, runStandardsChecks()...)
	}

	ui.Step(5, "Test coverage analysis")
	if opts.tests {
		results = append(results, runTestChecks()...)
	}

	ui.Step(6, "Dependency analysis")
	if opts.deps {
		results = append(results, runDependencyChecks()...)
	}

	ui.Blank()

	if analyzeOpts.output == "json" {
		printAnalyzeJSON(results)
	} else {
		printAnalyzeReport(results)
	}

	failed := analyzeCountByStatus(results, "✗")
	warned := analyzeCountByStatus(results, "⚠")
	passed := analyzeCountByStatus(results, "✓")
	total := len(results)

	ui.Blank()
	ui.Info(fmt.Sprintf("Analyzed %d rules — %d passed, %d warnings, %d failed", total, passed, warned, failed))

	if failed > 0 {
		return fmt.Errorf("analyze: %d rule(s) failed", failed)
	}
	if analyzeOpts.failOnWarn && warned > 0 {
		return fmt.Errorf("analyze: %d warning(s) (--fail-on-warn)", warned)
	}
	return nil
}

// resolveAnalyzeCategories enables all categories when none are explicitly selected.
func resolveAnalyzeCategories(opts analyzeOptions) analyzeOptions {
	any := opts.architecture || opts.quality || opts.security || opts.standards || opts.tests || opts.deps
	if !any {
		opts.architecture = true
		opts.quality = true
		opts.security = true
		opts.standards = true
		opts.tests = true
		opts.deps = true
	}
	return opts
}

func analyzeCountByStatus(results []analyzeResult, status string) int {
	n := 0
	for _, r := range results {
		if r.status == status {
			n++
		}
	}
	return n
}

func analyzeResultsByCategory(results []analyzeResult) map[string][]analyzeResult {
	m := make(map[string][]analyzeResult)
	for _, r := range results {
		m[r.category] = append(m[r.category], r)
	}
	return m
}

func printAnalyzeReport(results []analyzeResult) {
	byCategory := analyzeResultsByCategory(results)
	categories := []string{"Architecture", "Quality", "Security", "Standards", "Tests", "Dependencies"}

	for _, cat := range categories {
		items, ok := byCategory[cat]
		if !ok {
			continue
		}
		ui.Section(cat)
		rows := make([][]string, len(items))
		for i, r := range items {
			loc := r.file
			if loc == "" {
				loc = "project"
			}
			sug := r.suggestion
			if sug == "" {
				sug = "—"
			}
			rows[i] = []string{r.status, r.rule, loc, r.message, sug}
		}
		ui.Table([]string{"", "Rule", "Location", "Detail", "Suggestion"}, rows)
		ui.Blank()
	}
}

func printAnalyzeJSON(results []analyzeResult) {
	fmt.Println("[")
	for i, r := range results {
		comma := ","
		if i == len(results)-1 {
			comma = ""
		}
		fmt.Printf(
			`  {"category":%q,"rule":%q,"status":%q,"message":%q,"suggestion":%q,"file":%q}%s`+"\n",
			r.category, r.rule, r.status, r.message, r.suggestion, r.file, comma,
		)
	}
	fmt.Println("]")
}

// ─── small filesystem helpers shared across check files ──────────────────────

// analyzeGoFiles returns all .go files recursively under root, excluding test files when skipTests=true.
func analyzeGoFiles(root string, skipTests bool) ([]string, error) {
	var files []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if skipTests && strings.HasSuffix(path, "_test.go") {
			return nil
		}
		files = append(files, path)
		return nil
	})
	return files, err
}

// analyzeReadFile reads a file's content, returning empty string on error.
func analyzeReadFile(path string) string {
	b, err := os.ReadFile(path) //nolint:gosec // path is from filepath.Walk, not user input
	if err != nil {
		return ""
	}
	return string(b)
}

// dirExists returns true when the path exists and is a directory.
func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

// fileExists returns true when the path exists and is a regular file.
func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}
