package cmd

import (
	"fmt"
	"strings"
)

// generateChainMiddleware returns the middleware.go file with the Chain() helper.
func generateChainMiddleware(module string) string {
	var b strings.Builder
	b.WriteString("package middleware\n\n")
	b.WriteString("import \"net/http\"\n\n")
	b.WriteString("// Middleware is a function that wraps an http.Handler.\n")
	b.WriteString("type Middleware func(http.Handler) http.Handler\n\n")
	b.WriteString("// Chain composes multiple middleware functions into a single Middleware.\n")
	b.WriteString("// Middleware is applied in the order given, so the first argument is the\n")
	b.WriteString("// outermost wrapper.\n")
	b.WriteString("func Chain(mws ...Middleware) Middleware {\n")
	b.WriteString("\treturn func(final http.Handler) http.Handler {\n")
	b.WriteString("\t\tfor i := len(mws) - 1; i >= 0; i-- {\n")
	b.WriteString("\t\t\tfinal = mws[i](final)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn final\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// generateCORSMiddleware returns cors.go content.
func generateCORSMiddleware() string {
	var b strings.Builder
	b.WriteString("package middleware\n\n")
	b.WriteString("import \"net/http\"\n\n")
	b.WriteString("// CORSConfig holds CORS policy settings.\n")
	b.WriteString("type CORSConfig struct {\n")
	b.WriteString("\tAllowedOrigins []string\n")
	b.WriteString("\tAllowedMethods []string\n")
	b.WriteString("\tAllowedHeaders []string\n")
	b.WriteString("}\n\n")
	b.WriteString("// DefaultCORSConfig returns a permissive default configuration.\n")
	b.WriteString("func DefaultCORSConfig() CORSConfig {\n")
	b.WriteString("\treturn CORSConfig{\n")
	b.WriteString("\t\tAllowedOrigins: []string{\"*\"},\n")
	b.WriteString("\t\tAllowedMethods: []string{\"GET\", \"POST\", \"PUT\", \"DELETE\", \"OPTIONS\", \"PATCH\"},\n")
	b.WriteString("\t\tAllowedHeaders: []string{\"Content-Type\", \"Authorization\", \"X-Request-ID\"},\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("// CORS returns middleware that sets CORS headers based on the given config.\n")
	b.WriteString("func CORS(cfg CORSConfig) Middleware {\n")
	b.WriteString("\treturn func(next http.Handler) http.Handler {\n")
	b.WriteString("\t\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\t\t\torigin := r.Header.Get(\"Origin\")\n")
	b.WriteString("\t\t\tallowed := originAllowed(cfg.AllowedOrigins, origin)\n\n")
	b.WriteString("\t\t\tif allowed {\n")
	b.WriteString("\t\t\t\tw.Header().Set(\"Access-Control-Allow-Origin\", origin)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString(fmt.Sprintf("\t\t\tw.Header().Set(\"Access-Control-Allow-Methods\", joinStrings(cfg.AllowedMethods))\n"))
	b.WriteString(fmt.Sprintf("\t\t\tw.Header().Set(\"Access-Control-Allow-Headers\", joinStrings(cfg.AllowedHeaders))\n\n"))
	b.WriteString("\t\t\tif r.Method == http.MethodOptions {\n")
	b.WriteString("\t\t\t\tw.WriteHeader(http.StatusNoContent)\n")
	b.WriteString("\t\t\t\treturn\n")
	b.WriteString("\t\t\t}\n\n")
	b.WriteString("\t\t\tnext.ServeHTTP(w, r)\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("func originAllowed(allowed []string, origin string) bool {\n")
	b.WriteString("\tfor _, a := range allowed {\n")
	b.WriteString("\t\tif a == \"*\" || a == origin {\n")
	b.WriteString("\t\t\treturn true\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn false\n")
	b.WriteString("}\n\n")
	b.WriteString("func joinStrings(ss []string) string {\n")
	b.WriteString("\tresult := \"\"\n")
	b.WriteString("\tfor i, s := range ss {\n")
	b.WriteString("\t\tif i > 0 {\n")
	b.WriteString("\t\t\tresult += \", \"\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tresult += s\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn result\n")
	b.WriteString("}\n")
	return b.String()
}

// generateLoggingMiddleware returns logging.go content.
func generateLoggingMiddleware() string {
	var b strings.Builder
	b.WriteString("package middleware\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"log\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"time\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// statusWriter wraps http.ResponseWriter to capture the status code.\n")
	b.WriteString("type statusWriter struct {\n")
	b.WriteString("\thttp.ResponseWriter\n")
	b.WriteString("\tstatusCode int\n")
	b.WriteString("}\n\n")
	b.WriteString("func (sw *statusWriter) WriteHeader(code int) {\n")
	b.WriteString("\tsw.statusCode = code\n")
	b.WriteString("\tsw.ResponseWriter.WriteHeader(code)\n")
	b.WriteString("}\n\n")
	b.WriteString("// Logging returns middleware that logs each request with method, path,\n")
	b.WriteString("// status code, and duration.\n")
	b.WriteString("func Logging() Middleware {\n")
	b.WriteString("\treturn func(next http.Handler) http.Handler {\n")
	b.WriteString("\t\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\t\t\tstart := time.Now()\n")
	b.WriteString("\t\t\tsw := &statusWriter{ResponseWriter: w, statusCode: http.StatusOK}\n")
	b.WriteString("\t\t\tnext.ServeHTTP(sw, r)\n")
	b.WriteString("\t\t\tlog.Printf(\"%s %s %d %s\", r.Method, r.URL.Path, sw.statusCode, time.Since(start))\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// generateAuthMiddleware returns auth.go content (JWT validation).
func generateAuthMiddleware() string {
	var b strings.Builder
	b.WriteString("package middleware\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"strings\"\n\n")
	b.WriteString("\t\"github.com/golang-jwt/jwt/v5\"\n")
	b.WriteString(")\n\n")
	b.WriteString("type contextKey string\n\n")
	b.WriteString("const claimsKey contextKey = \"claims\"\n\n")
	b.WriteString("// ClaimsFromContext extracts JWT claims from the request context.\n")
	b.WriteString("func ClaimsFromContext(ctx context.Context) (jwt.MapClaims, bool) {\n")
	b.WriteString("\tc, ok := ctx.Value(claimsKey).(jwt.MapClaims)\n")
	b.WriteString("\treturn c, ok\n")
	b.WriteString("}\n\n")
	b.WriteString("// Auth returns middleware that validates a Bearer JWT token.\n")
	b.WriteString("// The secret is read from the JWT_SECRET environment variable.\n")
	b.WriteString("func Auth() Middleware {\n")
	b.WriteString("\treturn func(next http.Handler) http.Handler {\n")
	b.WriteString("\t\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\t\t\tauthHeader := r.Header.Get(\"Authorization\")\n")
	b.WriteString("\t\t\tif authHeader == \"\" || !strings.HasPrefix(authHeader, \"Bearer \") {\n")
	b.WriteString("\t\t\t\tjsonError(w, \"missing or invalid authorization header\", http.StatusUnauthorized)\n")
	b.WriteString("\t\t\t\treturn\n")
	b.WriteString("\t\t\t}\n\n")
	b.WriteString("\t\t\ttokenStr := strings.TrimPrefix(authHeader, \"Bearer \")\n")
	b.WriteString("\t\t\tsecret := os.Getenv(\"JWT_SECRET\")\n")
	b.WriteString("\t\t\tif secret == \"\" {\n")
	b.WriteString("\t\t\t\tjsonError(w, \"server misconfiguration: JWT_SECRET not set\", http.StatusInternalServerError)\n")
	b.WriteString("\t\t\t\treturn\n")
	b.WriteString("\t\t\t}\n\n")
	b.WriteString("\t\t\ttoken, err := jwt.Parse(tokenStr, func(t *jwt.Token) (interface{}, error) {\n")
	b.WriteString("\t\t\t\tif _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {\n")
	b.WriteString("\t\t\t\t\treturn nil, jwt.ErrSignatureInvalid\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\treturn []byte(secret), nil\n")
	b.WriteString("\t\t\t})\n")
	b.WriteString("\t\t\tif err != nil || !token.Valid {\n")
	b.WriteString("\t\t\t\tjsonError(w, \"invalid or expired token\", http.StatusUnauthorized)\n")
	b.WriteString("\t\t\t\treturn\n")
	b.WriteString("\t\t\t}\n\n")
	b.WriteString("\t\t\tclaims, ok := token.Claims.(jwt.MapClaims)\n")
	b.WriteString("\t\t\tif !ok {\n")
	b.WriteString("\t\t\t\tjsonError(w, \"invalid token claims\", http.StatusUnauthorized)\n")
	b.WriteString("\t\t\t\treturn\n")
	b.WriteString("\t\t\t}\n\n")
	b.WriteString("\t\t\tctx := context.WithValue(r.Context(), claimsKey, claims)\n")
	b.WriteString("\t\t\tnext.ServeHTTP(w, r.WithContext(ctx))\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("func jsonError(w http.ResponseWriter, msg string, code int) {\n")
	b.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	b.WriteString("\tw.WriteHeader(code)\n")
	b.WriteString("\t_ = json.NewEncoder(w).Encode(map[string]string{\"error\": msg})\n")
	b.WriteString("}\n")
	return b.String()
}

// generateRateLimitMiddleware returns rate_limit.go content.
func generateRateLimitMiddleware() string {
	var b strings.Builder
	b.WriteString("package middleware\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"net\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"sync\"\n\n")
	b.WriteString("\t\"golang.org/x/time/rate\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// RateLimitConfig holds per-IP rate limiter settings.\n")
	b.WriteString("type RateLimitConfig struct {\n")
	b.WriteString("\tRequestsPerSecond float64\n")
	b.WriteString("\tBurst             int\n")
	b.WriteString("}\n\n")
	b.WriteString("// DefaultRateLimitConfig returns sensible defaults (10 req/s, burst 20).\n")
	b.WriteString("func DefaultRateLimitConfig() RateLimitConfig {\n")
	b.WriteString("\treturn RateLimitConfig{\n")
	b.WriteString("\t\tRequestsPerSecond: 10,\n")
	b.WriteString("\t\tBurst:             20,\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("// RateLimit returns middleware that applies per-IP token bucket rate limiting.\n")
	b.WriteString("func RateLimit(cfg RateLimitConfig) Middleware {\n")
	b.WriteString("\tvar mu sync.Mutex\n")
	b.WriteString("\tlimiters := make(map[string]*rate.Limiter)\n\n")
	b.WriteString("\tgetLimiter := func(ip string) *rate.Limiter {\n")
	b.WriteString("\t\tmu.Lock()\n")
	b.WriteString("\t\tdefer mu.Unlock()\n")
	b.WriteString("\t\tif lim, ok := limiters[ip]; ok {\n")
	b.WriteString("\t\t\treturn lim\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tlim := rate.NewLimiter(rate.Limit(cfg.RequestsPerSecond), cfg.Burst)\n")
	b.WriteString("\t\tlimiters[ip] = lim\n")
	b.WriteString("\t\treturn lim\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn func(next http.Handler) http.Handler {\n")
	b.WriteString("\t\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\t\t\tip, _, _ := net.SplitHostPort(r.RemoteAddr)\n")
	b.WriteString("\t\t\tif ip == \"\" {\n")
	b.WriteString("\t\t\t\tip = r.RemoteAddr\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tif !getLimiter(ip).Allow() {\n")
	b.WriteString("\t\t\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	b.WriteString("\t\t\t\tw.WriteHeader(http.StatusTooManyRequests)\n")
	b.WriteString("\t\t\t\t_ = json.NewEncoder(w).Encode(map[string]string{\"error\": \"rate limit exceeded\"})\n")
	b.WriteString("\t\t\t\treturn\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tnext.ServeHTTP(w, r)\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// generateRecoveryMiddleware returns recovery.go content.
func generateRecoveryMiddleware() string {
	var b strings.Builder
	b.WriteString("package middleware\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"log\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"runtime/debug\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// Recovery returns middleware that recovers from panics and responds with\n")
	b.WriteString("// a 500 JSON error. When debugMode is true the stack trace is included.\n")
	b.WriteString("func Recovery(debugMode bool) Middleware {\n")
	b.WriteString("\treturn func(next http.Handler) http.Handler {\n")
	b.WriteString("\t\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\t\t\tdefer func() {\n")
	b.WriteString("\t\t\t\tif rec := recover(); rec != nil {\n")
	b.WriteString("\t\t\t\t\tstack := string(debug.Stack())\n")
	b.WriteString("\t\t\t\t\tlog.Printf(\"panic recovered: %v\\n%s\", rec, stack)\n\n")
	b.WriteString("\t\t\t\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	b.WriteString("\t\t\t\t\tw.WriteHeader(http.StatusInternalServerError)\n\n")
	b.WriteString("\t\t\t\t\tresp := map[string]string{\"error\": \"internal server error\"}\n")
	b.WriteString("\t\t\t\t\tif debugMode {\n")
	b.WriteString("\t\t\t\t\t\tresp[\"stack\"] = stack\n")
	b.WriteString("\t\t\t\t\t}\n")
	b.WriteString("\t\t\t\t\t_ = json.NewEncoder(w).Encode(resp)\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}()\n")
	b.WriteString("\t\t\tnext.ServeHTTP(w, r)\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// generateRequestIDMiddleware returns request_id.go content.
func generateRequestIDMiddleware() string {
	var b strings.Builder
	b.WriteString("package middleware\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"net/http\"\n\n")
	b.WriteString("\t\"github.com/google/uuid\"\n")
	b.WriteString(")\n\n")
	b.WriteString("const requestIDKey contextKey = \"request_id\"\n\n")
	b.WriteString("// RequestIDFromContext returns the request ID from the context.\n")
	b.WriteString("func RequestIDFromContext(ctx context.Context) string {\n")
	b.WriteString("\tif id, ok := ctx.Value(requestIDKey).(string); ok {\n")
	b.WriteString("\t\treturn id\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn \"\"\n")
	b.WriteString("}\n\n")
	b.WriteString("// RequestID returns middleware that injects a unique X-Request-ID header\n")
	b.WriteString("// into the request context and the response.\n")
	b.WriteString("func RequestID() Middleware {\n")
	b.WriteString("\treturn func(next http.Handler) http.Handler {\n")
	b.WriteString("\t\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\t\t\tid := r.Header.Get(\"X-Request-ID\")\n")
	b.WriteString("\t\t\tif id == \"\" {\n")
	b.WriteString("\t\t\t\tid = uuid.New().String()\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tw.Header().Set(\"X-Request-ID\", id)\n")
	b.WriteString("\t\t\tctx := context.WithValue(r.Context(), requestIDKey, id)\n")
	b.WriteString("\t\t\tnext.ServeHTTP(w, r.WithContext(ctx))\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// generateTimeoutMiddleware returns timeout.go content.
func generateTimeoutMiddleware() string {
	var b strings.Builder
	b.WriteString("package middleware\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"time\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// Timeout returns middleware that sets a context deadline on each request.\n")
	b.WriteString("func Timeout(d time.Duration) Middleware {\n")
	b.WriteString("\treturn func(next http.Handler) http.Handler {\n")
	b.WriteString("\t\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\t\t\tctx, cancel := context.WithTimeout(r.Context(), d)\n")
	b.WriteString("\t\t\tdefer cancel()\n")
	b.WriteString("\t\t\tnext.ServeHTTP(w, r.WithContext(ctx))\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}
