// Single source of truth for per-command marketing copy — used by both the
// static command-card generator and the per-command video generator.
// Grounded in the actual Goca CLI (verified against cmd/*.go).
export const COMMANDS = [
  { id: 'init', tag: 'PROJECT SCAFFOLDING', icon: 'package',
    headline: ['Zero to project', 'in one command.'],
    sub: ['Full Clean Architecture skeleton, database,', 'API style and auth chosen up front.'],
    cmd: '$ goca init shop --database postgres --api rest' },
  { id: 'feature', tag: 'ALL LAYERS', icon: 'rocket',
    headline: ['Idea to feature', 'in seconds.'],
    sub: ['One command scaffolds domain, use case,', 'repository and handler — fully wired.'],
    cmd: '$ goca feature Order --fields "id:string,total:float64"' },
  { id: 'entity', tag: 'DOMAIN LAYER', icon: 'layout',
    headline: ['Pure domain.', 'No exceptions.'],
    sub: ['Entities with validation and business rules', '— zero external dependencies.'],
    cmd: '$ goca entity User --fields "name:string,email:string"' },
  { id: 'usecase', tag: 'USE CASE LAYER', icon: 'refresh',
    headline: ['Business rules,', 'clearly scoped.'],
    sub: ['DTOs and operations generated per entity', '— create, read, update, delete, list.'],
    cmd: '$ goca usecase User --operations "create,read,update,delete"' },
  { id: 'repository', tag: 'REPOSITORY LAYER', icon: 'database',
    headline: ['Persistence,', 'fully swappable.'],
    sub: ['Interface and implementation generated', 'together — postgres, mysql, mongo & more.'],
    cmd: '$ goca repository User --database postgres --cache' },
  { id: 'handler', tag: 'HANDLER LAYER', icon: 'zap',
    headline: ['One entity,', 'any protocol.'],
    sub: ['HTTP, gRPC, CLI, worker or SOAP handlers', '— same use case underneath.'],
    cmd: '$ goca handler User --type http --middleware' },
  { id: 'di', tag: 'CROSS-CUTTING', icon: 'plug',
    headline: ['Wired together,', 'not by hand.'],
    sub: ['Dependency injection generated across', 'every feature — Wire-compatible.'],
    cmd: '$ goca di --features "User,Product" --wire' },
  { id: 'interfaces', tag: 'TDD-FIRST', icon: 'target',
    headline: ['Contracts first,', 'code second.'],
    sub: ['Generate interfaces alone, then implement', 'against them — true TDD.'],
    cmd: '$ goca interfaces User --all' },
  { id: 'messages', tag: 'CROSS-CUTTING', icon: 'book',
    headline: ['Consistent errors,', 'not copy-paste.'],
    sub: ['Error codes, response formats and constants', '— generated once, reused everywhere.'],
    cmd: '$ goca messages User --all' },
  { id: 'integrate', tag: 'CROSS-CUTTING', icon: 'gitbranch',
    headline: ['Generated features,', 'actually wired.'],
    sub: ['Bolt existing entities into DI and main.go', 'without touching them by hand.'],
    cmd: '$ goca integrate --features "User,Product"' },
  { id: 'middleware', tag: 'HANDLER LAYER', icon: 'shield',
    headline: ['CORS, logging,', 'recovery — done.'],
    sub: ['Standard HTTP middleware, generated as', 'a reusable package.'],
    cmd: '$ goca middleware auth --types "cors,logging,recovery"' },
  { id: 'mocks', tag: 'TESTING', icon: 'flask',
    headline: ['Mocks for every', 'interface.'],
    sub: ['Repository, use case and handler mocks', '— generated, not hand-maintained.'],
    cmd: '$ goca mocks User --all' },
  { id: 'test-integration', tag: 'TESTING', icon: 'flask',
    headline: ['Integration tests,', 'with real fixtures.'],
    sub: ['Database containers, fixtures and helpers', '— scaffolded per feature.'],
    cmd: '$ goca test-integration User --fixtures --container' },
  { id: 'ci', tag: 'DEVOPS', icon: 'gitbranch',
    headline: ['CI/CD, generated,', 'not googled.'],
    sub: ['GitHub Actions pipeline with Docker build', 'and deploy steps, out of the box.'],
    cmd: '$ goca ci --provider github-actions --with-docker' },
  { id: 'doctor', tag: 'DIAGNOSTICS', icon: 'activity',
    headline: ['Is your project', 'actually clean?'],
    sub: ['Diagnoses structure issues against Clean', 'Architecture rules — and can fix them.'],
    cmd: '$ goca doctor --fix' },
  { id: 'analyze', tag: 'DIAGNOSTICS', icon: 'search',
    headline: ['Architecture,', 'under a microscope.'],
    sub: ['Quality, security and standards checks', '— CI-friendly JSON output.'],
    cmd: '$ goca analyze --arch --quality --security' },
  { id: 'config', tag: 'CROSS-CUTTING', icon: 'settings',
    headline: ['.goca.yaml,', 'not tribal knowledge.'],
    sub: ['Show, validate or scaffold your project', 'config from the command line.'],
    cmd: '$ goca config validate' },
  { id: 'template', tag: 'TOOLING', icon: 'copy',
    headline: ['Your own', 'code templates.'],
    sub: ['Override Goca’s generators with templates', 'tailored to your team.'],
    cmd: '$ goca template init' },
  { id: 'upgrade', tag: 'CROSS-CUTTING', icon: 'arrowupcircle',
    headline: ['Stay current,', 'without the rewrite.'],
    sub: ['Upgrade project config and regenerate code', 'for the latest Goca version.'],
    cmd: '$ goca upgrade --regenerate feature --dry-run' },
  { id: 'mcp-server', tag: 'AI TOOLING', icon: 'bot',
    headline: ['Goca, wired', 'into your AI agent.'],
    sub: ['Exposes every generator as an MCP tool', 'for AI coding assistants.'],
    cmd: '$ goca mcp-server' },
  { id: 'version', tag: 'CLI', icon: 'book',
    headline: ['Know exactly', 'what’s installed.'],
    sub: ['Full build metadata, or just the version', 'string for scripts.'],
    cmd: '$ goca version --short' },
];
